consul:
  image: gliderlabs/consul-server
  container_name: consul
  restart: always
  command: -bootstrap-expect 1
  ports:
    - "8500:8500"
registrator:
  image: gliderlabs/registrator
  container_name: registrator
  restart: always
  links:
    - consul
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  command: consul://consul:8500
mongo:
  image: mongo:2.6
  container_name: mongo
  restart: always
  command: --smallfiles
  ports:
    - "27017:27017"
  volumes:
    - mongo_data:/data/db
node-movies:
  image: dockerottawa/node-movies
  container_name: node-movies
  restart: always
  links:
    - mongo
  environment:
    - MONGO_URL=mongodb://mongo:27017/test
  ports:
    - "3000:3000"
